Added default multi-platform builds for amd64 and arm64 docker images.
hathitrust/github_actions pull request #7
Opened 2024-02-23 20:46 UTC by Ronster2018

The way this branch currently works is that there are two default platforms it will build; both ARM64 and AMD64 images. The `platforms` argument may be omitted from the parent job that calls this composite action and it will still generate those images.

2024-02-26 14:09 UTC, aelkiss commented
Let's see if we can get the github-script, checkout, & login actions updated so they don't give deprecation warnings.

2024-02-26 14:24 UTC, aelkiss commented
For multi-platform builds let's see how well the caching works - if it's pretty quick to build both platforms assuming that only the repository (and not dependencies) have changed then I think it makes sense to enable by default

2024-02-26 14:25 UTC, aelkiss requested changes
Would like to see the dependencies updated but otherwise looks good, and we can see about caching speedups for multiplatform builds.

2024-02-29 15:18 UTC, aelkiss requested changes
I took a look at the runs from https://github.com/hathitrust/ht_indexer/actions and there are a few things I'd like to try:

* The run at https://github.com/hathitrust/ht_indexer/actions/runs/8053393423 still uses the deprecated node version; it looks like that's been addressed here, but I'd like to see an example of a run that uses this version to verify we don't get any deprecation warnings & that everything works as expected

* Likewise in https://github.com/hathitrust/ht_indexer/actions/runs/8053393423/job/21995701014 it ran so quickly not because it was taking advantage of the cache but because the output image tag already existed (https://github.com/hathitrust/ht_indexer/actions/runs/8053393423/job/21995701014#step:3:248). I'd like to see a run of the action that exercises the cache functionality.

Also looking at that same run, I would suggest a couple of other changes:
* do `docker/login-action@v3` before checking if the image exists - I think if it's a private image then it will always say it does not exist if we do `docker manifest inspect` without logging in or otherwise might have issues
* add `if: ${{ steps.image_check.outputs.image_exists != 'true' }}` for `setup-qemu-action` and `setup-buildx-action` since we only need to do that if we're actually going to build an image.

2024-03-11 14:07 UTC, aelkiss reviewed
Makes sense to me as we discussed, although we should hold off on merging this until:

1. we're happy with how this looks like when it gets called
2. we're certain (esp. with the changes in tagging) whether it's backwards-compatible or needs a new version

2024-03-13 15:03 UTC, aelkiss approved these changes
Moving the logic here looks good & with the test cases @Ronster2018 mentioned (might might be worth putting a link here) these should be ready to go.

2024-03-13 18:30 UTC, Ronster2018 commented
Test Cases:
- Trigger build from Run Tests workflow :white_check_mark:
  - Builds w/ or without Latest :white_check_mark: (Depends on workflow)
    - On push event [tests.yml](https://github.com/hathitrust/actions_playground/actions/runs/8237908910)
    - Listening for success from  [build.yaml](https://github.com/hathitrust/actions_playground/actions/runs/8237911364)

- Trigger manual build
  - rebuild :white_check_mark: (Adds tags to the image but doesn't remove them. Is that needed?)
  - [Build w/ latest tag](https://github.com/hathitrust/actions_playground/actions/runs/8268750277):white_check_mark:
  - [Build w/ unstable tag](https://github.com/hathitrust/actions_playground/actions/runs/8268556257) :white_check_mark:
  - [Build w/ latest or unstable tag & an additional tag like v1.0.0](https://github.com/hathitrust/actions_playground/actions/runs/8251317147) :white_check_mark:

2024-03-13 20:00 UTC, merged